# @package _global_

#### Model params #############################################################
model:
  name: rnn
  hparams: {}
  encoder:
    name: rnn
    hparams:
      hidden_size: 64
      n_layers: 1
  decoder:
    name: multiquantile
    hparams:
      hidden_size: ${model.encoder.hparams.hidden_size}
