# @package _global_

#### Model params #############################################################
model:
  name: stgnn
  hparams:
    hidden_size: 32
    emb_size: 16
    temporal_layers: 1
    gnn_layers: 2
    activation: 'elu'

dataset:
  connectivity:
    layout: csr
    include_self: False