# @package _global_

#### Model params #############################################################
model:
  name: transformer
  hparams:
    hidden_size: 32
    ff_size: 64
    n_heads: 2
    n_layers: 3
    dropout: 0.1