# @package _global_

#### Dataset params ###########################################################
dataset:
  name: air
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index

#### Windowing params #########################################################
window: 24
horizon: 1 #3
stride: 1
delay: 2

scale_target: True
add_exogenous: True