# @package _global_

#### Dataset params ###########################################################
dataset:
  name: la
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: edge_index

#### Windowing params #########################################################
window: 12
horizon: 1 #12
stride: 1
delay: 11

scale_target: False
add_exogenous: True